version: "3.9"  # optional since v1.27.0
services:
  app-server:
    build:
      context: /Users/gmp/spring
      dockerfile: Dockerfile
    ports:
      - "8089:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/shop?useUnicode=true&characterEncoding=utf8&useSSL=false
      SPRING_DATASOURCE_USERNAME: root

    networks:
      - backend
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: shop
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
    networks:
      - backend

networks:
  backend:
